### ISSUE TITLE
Get-ADInfo.ps1 forests with multiple alternate UPN suffixes

### ISSUE THREAD

**Issue by cunninghamp** [cunninghamp/Powershell-Exchange#1]
Script does not return a proper result for forests with multiple additional UPN suffixes.

**Comment by chrislehr** [comment]
Paul - can you add this function call to fetch Exchange schema/forest/domain prep - source:
Comments here: https://blogs.technet.microsoft.com/rmilne/2015/03/17/how-to-check-exchange-schema-and-object-values-in-ad/

function Get-ExchSchemaAndObjectValues
{
# Author: Keith Smith
# Email: Keith.J.Smith@outlook.com
# Date: 03.27.2017
# Import Active Directory Module for users with older versions of PowerShell
Import-Module ActiveDirectory
# Pull Exchange Info from AD and put it into an object
$obj = New-Object PSObject
Add-Member -InputObject $obj -MemberType NoteProperty -Name msExchProductId -Value “$($(Get-ADObject “CN=Exchange,CN=Microsoft Exchange,CN=Services,$((Get-ADRootDSE).configurationNamingContext)” -Property msExchProductId).msExchProductId)”
Add-Member -InputObject $obj -MemberType NoteProperty -Name RangeUpper -Value “$($(Get-ADObject “CN=ms-Exch-Schema-Version-Pt,$((Get-ADRootDSE).schemaNamingContext)” -Property Rangeupper).RangeUpper)”
Add-Member -InputObject $obj -MemberType NoteProperty -Name objectVersion -Value “$($(Get-ADObject “CN=Microsoft Exchange System Objects,$((Get-ADRootDSE).defaultNamingContext)” -Property objectVersion).objectVersion)”
Add-Member -InputObject $obj -MemberType NoteProperty -Name OrganisationobjectVersion -Value “$($(Get-ADObject “CN=Exchange,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=corp,DC=prod” -Property objectVersion).ObjectVersion)”
#$obj
# Output information to screen after clearing it
CLS
Write-output “”
Write-output “Compare the below results to Rhoderick Milne’s Table Of Exchange 2013 Schema Versions”
Write-output “https://blogs.technet.microsoft.com/rmilne/2015/03/17/how-to-check-exchange-schema-and-object-values-in-ad/”
Write-output “”
$obj
}
Get-ExchSchemaAndObjectValues

**Comment by cunninghamp** [comment]
I really won't have time, sorry. But if you or someone wants to fork the script and add the code (and test it) I'm happy to look at a PR.
